apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-ci
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/shyma27/MERN-CRUD-DEVOPS.git
    targetRevision: backend
    path: local_deploy/kuber(k3s)
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
      automated:
        prune: true
        selfHeal: true