apiVersion: v1
kind: Service
metadata:
  name: backend-service 
  labels:
    app: backend-service 
spec:
  ports:
  - port: 8080
    targetPort: back-app-port 
    name: back-service-port 
  clusterIP: None
  selector:
    app: backend