apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: shymauno/myrepo:node-lts-alpine3.22-backend-mern-crud-devops-fd87cba
        ports:
        - containerPort: 8080
          name: back-app-port
        # resources:
        #   requests:
        #     memory: "256Mi"
        #     cpu: "256Mi"
        env:
        - name: MONGODB_URI
          value: mongodb://mongodb-service:27017/MERN
      imagePullSecrets:
      - name: docker-auth
