apiVersion: v1
kind: Service
metadata:
  name: mongodb-service #name of the service, can be put to DB connection string for e.g
  labels:
    app: mongodb-service #label of service to filter it via kubectl (kubectl get svc -l app=mongodb-service)
spec:
  ports:
  - port: 27017 #port service listens to, forwards requests to Pod container port
    targetPort: db-port #port of the container (defined in db-statefulset.yaml)
    name: db-service-port #port name. can be targeted by other objects
  clusterIP: None #Headless service. instead of giving you one IP, the DNS will return the direct IP addresses of all the individual MongoDB Pods.
  selector:
    app: mongodb #select Pods with this label