apiVersion: v1
kind: Service
metadata:
  name: frontend-service 
  labels:
    app: frontend-service 
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: front-app-port 
    nodePort: 30007
    name: front-service-port 
  selector:
    app: frontend