Vagrant.configure("2") do |config|
  #K3s_URL = ENV['K3S_URL']
  #K3S_TOKEN = ENV['K3S_TOKEN']
  K3S_URL = "https://10.0.0.8:6443"
  K3S_TOKEN = "MySuperSecretToken"

  config.vm.define "control" do |control|
    control.vm.box = "bento/ubuntu-22.04"
    control.vm.box_version = "202510.26.0"
    control.vm.hostname = "control"
    control.vm.network "private_network", ip: "10.0.0.8"
    control.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end
    control.vm.provision "shell", env: {"K3S_TOKEN" => K3S_TOKEN}, inline: <<-SHELL
      curl -sfL https://get.k3s.io | K3S_TOKEN=$K3S_TOKEN sh -s - server --node-ip=10.0.0.8
    SHELL
  end

  config.vm.define "agent" do |agent|
    agent.vm.box = "bento/ubuntu-22.04"
    agent.vm.box_version = "202510.26.0"
    agent.vm.hostname = "agent"
    agent.vm.network "private_network", ip: "10.0.0.7"
    agent.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
    agent.vm.provision "shell", env: {"K3S_URL" => K3S_URL, "K3S_TOKEN" => K3S_TOKEN}, privileged: false, inline: <<-SHELL
      curl -sfL https://get.k3s.io | K3S_URL=$K3S_URL K3S_TOKEN=$K3S_TOKEN sh -s - agent --node-ip=10.0.0.7
    SHELL
  end
  
end