Vagrant.configure("2") do |config|
  k3s_url = ENV['K3S_URL']
  k3s_token = ENV['K3S_TOKEN']

  config.vm.define "agent" do |agent|
    agent.vm.box = "bento/ubuntu-22.04"
    agent.vm.box_version = "202510.26.0"
    agent.vm.hostname = "agent"
    agent.vm.network "private_network", ip: "10.0.0.7"

    agent.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end

    agent.vm.provision "shell", privileged: false, inline: <<-SHELL
      curl -sfL https://get.k3s.io | K3S_URL=#{k3s_url} K3S_TOKEN=#{k3s_token} sh -
    SHELL
  end
end