FROM node:lts-alpine3.22 AS build
WORKDIR /app
COPY ./client/ ./
RUN set -eux && \
    npm install && \
    npm run build

FROM nginx:1.28.2-alpine3.23
COPY ./local_deploy/default.conf /etc/nginx/conf.d/
COPY --from=build /app/build/ /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]