Vagrant.configure("2") do |config|
  config.vm.define "db" do |db| 
    db.vm.box = "bento/ubuntu-24.04"
    db.vm.box_version = "202510.26.0"
    db.vm.hostname = "db"
    db.vm.network "private_network", ip: "10.0.0.1"
    db.vm.network "forwarded_port", guest: 27017, host: 27017
    
    db.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end

    db.vm.provision "shell", path: "mongo.sh" 
  end

  config.vm.define "front" do |front|
    front.vm.box = "bento/ubuntu-24.04"
    front.vm.box_version = "202510.26.0"
    front.vm.hostname = "front"
    front.vm.network "private_network", ip: "10.0.0.2"
    front.vm.network "forwarded_port", guest: 80, host: 80
    
    front.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end

    front.vm.synced_folder "../client", "/home/vagrant/front",
      owner: "vagrant", group: "vagrant"

    front.vm.provision "shell", path: "node.sh", privileged: false
  end

  config.vm.define "back" do |back|
    back.vm.box = "bento/ubuntu-24.04"
    back.vm.box_version = "202510.26.0"
    back.vm.hostname = "back"
    back.vm.network "private_network", ip: "10.0.0.3"
    back.vm.network "forwarded_port", guest: 8080, host: 8081
    
    back.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end

    back.vm.synced_folder "../server", "/home/vagrant/back",
      owner: "vagrant", group: "vagrant"

    back.vm.provision "shell", path: "node.sh", privileged: false
  end

end