Vagrant.configure("2") do |config|
  config.vm.define "db" do |db| 
    db.vm.box = "bento/ubuntu-24.04"
    db.vm.box_version = "202510.26.0"
    db.vm.hostname = "db"
    db.vm.network "private_network", ip: "10.0.0.4"
    db.vm.network "forwarded_port", guest: 27017, host: 27017
    
    db.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
  end

  config.vm.define "frontend" do |frontend|
    frontend.vm.box = "bento/ubuntu-24.04"
    frontend.vm.box_version = "202510.26.0"
    frontend.vm.hostname = "front"
    frontend.vm.network "private_network", ip: "10.0.0.5"
    frontend.vm.network "forwarded_port", guest: 80, host: 80
    
    frontend.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end

    frontend.vm.synced_folder "../../client", "/home/vagrant/front",
      owner: "vagrant", group: "vagrant"
  end

  config.vm.define "backend" do |backend|
    backend.vm.box = "bento/ubuntu-24.04"
    backend.vm.box_version = "202510.26.0"
    backend.vm.hostname = "back"
    backend.vm.network "private_network", ip: "10.0.0.6"
    backend.vm.network "forwarded_port", guest: 8080, host: 8080
    
    backend.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end

    backend.vm.synced_folder "../../server", "/home/vagrant/back",
      owner: "vagrant", group: "vagrant"
  end

end